import { Medicine } from '../types';

/**
 * 10 Standalone Dedicated Dummy Store Products attached with Server / Storefront
 * Includes real high-res medical imagery, complete descriptions, categories, pricing, and badges.
 */
export const SERVER_DUMMY_STORE_PRODUCTS: Medicine[] = [
  {
    id: 'store-prod-01',
    barcode: '8964000120011',
    name: 'Panadol Extra 500mg Tablets',
    batchNumber: 'PAN-882',
    manufacturer: 'GlaxoSmithKline (GSK)',
    category: 'General Medicines',
    unit: 'STRIP',
    genericId: 'gen-paracetamol',
    genericName: 'Paracetamol + Caffeine',
    strength: '500mg',
    dosageForm: 'Tablet',
    isControlled: false,
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365).toISOString(),
    quantity: 450,
    lowStockThreshold: 50,
    purchasePrice: 380,
    mrp: 480,
    sellingPrice: 420,
    gstPercentage: 0,
    showOnline: true,
    showInOnlineStore: true,
    onlineStatus: 'Published',
    onlineSaleAllowed: true,
    onlineName: 'Panadol Extra 500mg (Pack of 10 Strips)',
    onlineDescription: 'Fast-acting dual action pain relief for headache, fever, joint aches, toothache, and flu symptoms. Trusted GSK formulation.',
    onlineImages: ['https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'General Medicines',
    onlinePrice: 420,
    compareAtPrice: 480,
    isFeatured: true,
    onlineBadge: 'Best Seller',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'store-prod-02',
    barcode: '8964000120028',
    name: 'Augmentin 625mg Antibiotic Tablets',
    batchNumber: 'AUG-904',
    manufacturer: 'GlaxoSmithKline (GSK)',
    category: 'General Medicines',
    unit: 'BOX',
    genericName: 'Amoxicillin + Clavulanate Potassium',
    strength: '625mg',
    dosageForm: 'Tablet',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 280).toISOString(),
    quantity: 120,
    lowStockThreshold: 25,
    purchasePrice: 280,
    mrp: 350,
    sellingPrice: 310,
    gstPercentage: 0,
    showOnline: true,
    showInOnlineStore: true,
    onlineStatus: 'Published',
    onlineSaleAllowed: true,
    onlineName: 'Augmentin 625mg Antibiotic Tablets (6s)',
    onlineDescription: 'Broad-spectrum antibiotic formulation prescribed for chest, ear, sinus, skin, and throat bacterial infections.',
    onlineImages: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'General Medicines',
    onlinePrice: 310,
    compareAtPrice: 350,
    isFeatured: true,
    onlineBadge: 'Rx Required',
    requiresPrescription: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'store-prod-03',
    barcode: '8964000190073',
    name: 'Digital Upper Arm Blood Pressure Monitor',
    batchNumber: 'BPS-88',
    manufacturer: 'Omron / MediPlus Health Tech',
    category: 'Diagnostic Devices',
    unit: 'SET',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 720).toISOString(),
    quantity: 45,
    lowStockThreshold: 5,
    purchasePrice: 1800,
    mrp: 2800,
    sellingPrice: 2400,
    gstPercentage: 0,
    showOnline: true,
    showInOnlineStore: true,
    onlineStatus: 'Published',
    onlineSaleAllowed: true,
    onlineName: 'Omron Digital Automatic Upper Arm BP Monitor',
    onlineDescription: 'High accuracy clinical blood pressure testing device with large LCD backlit screen, irregular pulse alert, and memory log for 2 users.',
    onlineImages: ['https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'Diagnostic Devices',
    onlinePrice: 2400,
    compareAtPrice: 2800,
    isFeatured: true,
    onlineBadge: 'Top Rated',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'store-prod-04',
    barcode: '8964000120088',
    name: 'Surbex Z Multivitamin + Zinc (30s)',
    batchNumber: 'SZ-309',
    manufacturer: 'Abbott Laboratories',
    category: 'General Medicines',
    unit: 'BOTTLE',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 500).toISOString(),
    quantity: 180,
    lowStockThreshold: 30,
    purchasePrice: 320,
    mrp: 420,
    sellingPrice: 380,
    gstPercentage: 0,
    showOnline: true,
    showInOnlineStore: true,
    onlineStatus: 'Published',
    onlineSaleAllowed: true,
    onlineName: 'Surbex Z Multivitamin + Zinc (30 Tablets Bottle)',
    onlineDescription: 'High potency B-Complex formula enriched with Zinc, Vitamin C, and Vitamin E for immunity, vitality, and stamina.',
    onlineImages: ['https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'General Medicines',
    onlinePrice: 380,
    compareAtPrice: 420,
    isFeatured: true,
    onlineBadge: 'Immunity Special',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'store-prod-05',
    barcode: '8964000190099',
    name: 'Fingertip OLED Pulse Oximeter',
    batchNumber: 'OXI-2026',
    manufacturer: 'Contec Medical',
    category: 'Diagnostic Devices',
    unit: 'PCS',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 800).toISOString(),
    quantity: 60,
    lowStockThreshold: 10,
    purchasePrice: 1100,
    mrp: 1800,
    sellingPrice: 1500,
    gstPercentage: 0,
    showOnline: true,
    showInOnlineStore: true,
    onlineStatus: 'Published',
    onlineSaleAllowed: true,
    onlineName: 'Fingertip OLED Pulse Oximeter (SpO2 & Pulse)',
    onlineDescription: 'Instant non-invasive measurement of blood oxygen saturation level (SpO2) and pulse rate with multi-directional dual-color OLED screen.',
    onlineImages: ['https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'Diagnostic Devices',
    onlinePrice: 1500,
    compareAtPrice: 1800,
    isFeatured: true,
    onlineBadge: 'Hot Item',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'store-prod-06',
    barcode: '8964000190022',
    name: 'Infrared Non-Contact Forehead Thermometer',
    batchNumber: 'THM-551',
    manufacturer: 'Berrcom Medical Tech',
    category: 'Diagnostic Devices',
    unit: 'PCS',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 900).toISOString(),
    quantity: 75,
    lowStockThreshold: 10,
    purchasePrice: 1300,
    mrp: 2300,
    sellingPrice: 1850,
    gstPercentage: 0,
    showOnline: true,
    showInOnlineStore: true,
    onlineStatus: 'Published',
    onlineSaleAllowed: true,
    onlineName: 'Infrared Non-Contact Digital Forehead Thermometer',
    onlineDescription: '1-second instant fever check thermometer with color-coded fever alarm screen, silent night mode, and memory recall.',
    onlineImages: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'Diagnostic Devices',
    onlinePrice: 1850,
    compareAtPrice: 2300,
    isFeatured: true,
    onlineBadge: 'Clinically Tested',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'store-prod-07',
    barcode: '8964000190011',
    name: '10CC Disposable Sterile Syringes (Pack of 100)',
    batchNumber: 'BIO-10C',
    manufacturer: 'Bio-Care Surgical',
    category: 'Syringes',
    unit: 'BOX',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 500).toISOString(),
    quantity: 250,
    lowStockThreshold: 20,
    purchasePrice: 950,
    mrp: 1400,
    sellingPrice: 1200,
    gstPercentage: 0,
    showOnline: true,
    showInOnlineStore: true,
    onlineStatus: 'Published',
    onlineSaleAllowed: true,
    onlineName: 'Bio-Care 10CC Sterile Disposable Syringes (100s)',
    onlineDescription: 'EO Gas sterilized non-toxic single-use medical syringes with ultra-sharp German steel needles.',
    onlineImages: ['https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'Syringes',
    onlinePrice: 1200,
    compareAtPrice: 1400,
    isFeatured: true,
    onlineBadge: 'Bulk Surgical',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'store-prod-08',
    barcode: '8964000190033',
    name: 'Accu-Chek Glucose Meter Kit with 10 Test Strips',
    batchNumber: 'ACU-902',
    manufacturer: 'Roche Diabetes Care',
    category: 'Diagnostic Devices',
    unit: 'KIT',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 600).toISOString(),
    quantity: 50,
    lowStockThreshold: 8,
    purchasePrice: 2200,
    mrp: 3500,
    sellingPrice: 2950,
    gstPercentage: 0,
    showOnline: true,
    showInOnlineStore: true,
    onlineStatus: 'Published',
    onlineSaleAllowed: true,
    onlineName: 'Accu-Chek Instant Blood Glucose Meter Starter Kit',
    onlineDescription: 'Complete diabetes blood glucose monitor kit with lancing device, 10 sterile test strips, lancets, and protective carrying case.',
    onlineImages: ['https://images.unsplash.com/photo-1616671285420-7f28f0ee0038?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'Diagnostic Devices',
    onlinePrice: 2950,
    compareAtPrice: 3500,
    isFeatured: true,
    onlineBadge: 'Diabetes Care',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'store-prod-09',
    barcode: '8964000190044',
    name: 'Complete Emergency First Aid Box Kit',
    batchNumber: 'FAK-101',
    manufacturer: 'MediSafety Supplies',
    category: 'Bandages & Dressing',
    unit: 'KIT',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 730).toISOString(),
    quantity: 90,
    lowStockThreshold: 15,
    purchasePrice: 1100,
    mrp: 2000,
    sellingPrice: 1650,
    gstPercentage: 0,
    showOnline: true,
    showInOnlineStore: true,
    onlineStatus: 'Published',
    onlineSaleAllowed: true,
    onlineName: 'Complete Emergency Home & Office First Aid Kit',
    onlineDescription: 'Wall-mountable emergency first aid kit equipped with pyodine lotion, cotton rolls, gauze, adhesive plasters, trauma scissors, and burns ointment.',
    onlineImages: ['https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'Bandages & Dressing',
    onlinePrice: 1650,
    compareAtPrice: 2000,
    isFeatured: true,
    onlineBadge: 'Home Essential',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'store-prod-10',
    barcode: '8964000190055',
    name: 'N95 5-Layer Protective Face Masks (Pack of 20)',
    batchNumber: 'N95-404',
    manufacturer: '3M / SafeGuard Corp',
    category: 'Surgical Items',
    unit: 'BOX',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 800).toISOString(),
    quantity: 300,
    lowStockThreshold: 50,
    purchasePrice: 500,
    mrp: 1200,
    sellingPrice: 850,
    gstPercentage: 0,
    showOnline: true,
    showInOnlineStore: true,
    onlineStatus: 'Published',
    onlineSaleAllowed: true,
    onlineName: 'N95 5-Layer High Filtration Respirator Face Masks (20s)',
    onlineDescription: '5-ply meltblown protective respirator masks with 99% bacterial filtration efficiency, flexible nose bridge wire, and soft elastic ear loops.',
    onlineImages: ['https://images.unsplash.com/photo-1584634731339-252c581abfc5?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'Surgical Items',
    onlinePrice: 850,
    compareAtPrice: 1200,
    isFeatured: true,
    onlineBadge: '99% Filtration',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
