import { v4 as uuidv4 } from 'uuid';
import { 
  dbMedicines, dbSuppliers, dbInvoices, dbPurchaseOrders, 
  dbPartyPayments, dbExpenses, dbBankAccounts, dbBankTransactions, dbCheques, dbLoanAccounts,
  dbAppUsers, dbUserActivities, dbOnlineOrders, dbOnlinePromotions, dbStoreSettings,
  factoryResetAllStores
} from './db';
import { 
  Medicine, Supplier, Party, Invoice, PurchaseOrder, 
  PartyPayment, Expense, BankAccount, BankTransaction, ChequeRecord, LoanAccount,
  AppUserRecord, UserActivityLog, OnlineOrder
} from '../types';
import { DEFAULT_STORE_SETTINGS, DEFAULT_PROMOTIONS } from './storeManager';
import { SERVER_DUMMY_STORE_PRODUCTS } from './dummyStoreProducts';


export const DUMMY_MEDICINES: Medicine[] = [
  ...SERVER_DUMMY_STORE_PRODUCTS,
  {
    id: 'med-01',
    barcode: '8964000120011',
    name: 'Panadol Extra 500mg Tablets',
    batchNumber: 'PAN-882',
    manufacturer: 'GlaxoSmithKline (GSK)',
    category: 'General Medicines',
    unit: 'STRIP',
    genericId: 'gen-paracetamol',
    genericName: 'Paracetamol + Caffeine',
    strength: '500mg',
    dosageForm: 'Tablet',
    isControlled: false,
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365).toISOString(),
    quantity: 450,
    lowStockThreshold: 50,
    purchasePrice: 380,
    mrp: 480,
    sellingPrice: 420,
    gstPercentage: 0,
    showOnline: true,
    onlineStatus: 'Published',
    onlineName: 'Panadol Extra 500mg (Pack of 10 Strips)',
    onlineDescription: 'Fast-acting pain relief for headache, fever, joint aches, and flu symptoms. Trusted GSK formulation.',
    onlineImages: ['https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'General Medicines',
    onlinePrice: 420,
    compareAtPrice: 480,
    isFeatured: true,
    onlineBadge: 'Best Seller',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-02',
    barcode: '8964000120028',
    name: 'Augmentin 625mg Tablets',
    batchNumber: 'AUG-904',
    manufacturer: 'GlaxoSmithKline (GSK)',
    category: 'Antibiotics',
    unit: 'BOX',
    genericName: 'Amoxicillin + Clavulanate Potassium',
    strength: '625mg',
    dosageForm: 'Tablet',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 280).toISOString(),
    quantity: 120,
    lowStockThreshold: 25,
    purchasePrice: 280,
    mrp: 350,
    sellingPrice: 310,
    gstPercentage: 0,
    showOnline: true,
    onlineStatus: 'Published',
    onlineName: 'Augmentin 625mg Antibiotic Tablets (6s)',
    onlineDescription: 'Broad-spectrum antibiotic prescribed for bacterial infections. Requires doctor prescription upload.',
    onlineImages: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'General Medicines',
    onlinePrice: 310,
    compareAtPrice: 350,
    isFeatured: true,
    onlineBadge: 'Rx Required',
    requiresPrescription: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-bp-set',
    barcode: '8964000190073',
    name: 'Digital Blood Pressure Monitor (Omron / MediPlus)',
    batchNumber: 'BPS-88',
    manufacturer: 'MediPlus Health Tech',
    category: 'Diagnostic Devices',
    unit: 'SET',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 720).toISOString(),
    quantity: 45,
    lowStockThreshold: 5,
    purchasePrice: 1800,
    mrp: 2600,
    sellingPrice: 2400,
    gstPercentage: 0,
    showOnline: true,
    onlineStatus: 'Published',
    onlineName: 'Digital Automatic Upper Arm BP Monitor',
    onlineDescription: 'High accuracy clinical digital blood pressure check device with irregular heartbeat detector and memory storage.',
    onlineImages: ['https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'Diagnostic Devices',
    onlinePrice: 2400,
    compareAtPrice: 2800,
    isFeatured: true,
    onlineBadge: 'Top Rated',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-surbex-z',
    barcode: '8964000120088',
    name: 'Surbex Z Zinc Multivitamin Tablets',
    batchNumber: 'SZ-309',
    manufacturer: 'Abbott Laboratories',
    category: 'Supplements',
    unit: 'BOTTLE',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 500).toISOString(),
    quantity: 180,
    lowStockThreshold: 30,
    purchasePrice: 320,
    mrp: 420,
    sellingPrice: 380,
    gstPercentage: 0,
    showOnline: true,
    onlineStatus: 'Published',
    onlineName: 'Surbex Z Multivitamin + Zinc (30 Tablets)',
    onlineDescription: 'High potency Vitamin B-Complex with Zinc and Vitamin C for immune support and daily energy boost.',
    onlineImages: ['https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'General Medicines',
    onlinePrice: 380,
    compareAtPrice: 420,
    isFeatured: true,
    onlineBadge: 'Immunity Special',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-10cc-bio',
    barcode: '8964000190011',
    name: '10CC Disposable Sterile Syringes (Pack of 100)',
    batchNumber: 'BIO-10C',
    manufacturer: 'Bio-Care Surgical',
    category: 'Syringes',
    unit: 'BOX',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 500).toISOString(),
    quantity: 250,
    lowStockThreshold: 20,
    purchasePrice: 950,
    mrp: 1400,
    sellingPrice: 1200,
    gstPercentage: 0,
    showOnline: true,
    onlineStatus: 'Published',
    onlineName: 'Bio-Care 10CC Sterile Disposable Syringes (100s)',
    onlineDescription: 'EO Gas sterilized non-toxic single-use medical syringes with ultra-sharp German steel needles.',
    onlineImages: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'Syringes',
    onlinePrice: 1200,
    compareAtPrice: 1400,
    isFeatured: true,
    onlineBadge: 'Bulk Surgical',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-5-1000-uni',
    barcode: '8964000190028',
    name: 'Dextrose 5% 1000ML Infusion Bottle',
    batchNumber: 'UNI-1000',
    manufacturer: 'Uni-Pack Healthcare',
    category: 'IV Infusions',
    unit: 'BOTTLE',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 400).toISOString(),
    quantity: 110,
    lowStockThreshold: 20,
    purchasePrice: 120,
    mrp: 160,
    sellingPrice: 140,
    gstPercentage: 0,
    showOnline: true,
    onlineStatus: 'Published',
    onlineName: 'Dextrose 5% IV Infusion 1000ml (Sterile)',
    onlineDescription: 'Sterile intravenous fluid solution for hydration and calorie replenishment. Hospital grade.',
    onlineImages: ['https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'IV Infusions',
    onlinePrice: 140,
    compareAtPrice: 160,
    isFeatured: false,
    requiresPrescription: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-oximeter',
    barcode: '8964000190099',
    name: 'Fingertip Pulse Oximeter OLED Display',
    batchNumber: 'OXI-2026',
    manufacturer: 'Contec Medical',
    category: 'Diagnostic Devices',
    unit: 'PCS',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 800).toISOString(),
    quantity: 60,
    lowStockThreshold: 10,
    purchasePrice: 1100,
    mrp: 1800,
    sellingPrice: 1500,
    gstPercentage: 0,
    showOnline: true,
    onlineStatus: 'Published',
    onlineName: 'OLED Digital Fingertip Pulse Oximeter (SpO2 & Pulse)',
    onlineDescription: 'Instant accurate blood oxygen saturation level (SpO2) and pulse rate monitor with dual-color LED screen.',
    onlineImages: ['https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=800&q=80'],
    onlineCategory: 'Diagnostic Devices',
    onlinePrice: 1500,
    compareAtPrice: 1800,
    isFeatured: true,
    onlineBadge: 'Hot Item',
    requiresPrescription: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-03',
    barcode: '8964000120035',
    name: 'Disprin 300mg Tablets',
    batchNumber: 'DSP-412',
    manufacturer: 'Reckitt Benckiser',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 400).toISOString(),
    quantity: 300,
    lowStockThreshold: 40,
    purchasePrice: 170,
    mrp: 230,
    sellingPrice: 195,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-04',
    barcode: '8964000120042',
    name: 'Flagyl 400mg Tablets',
    batchNumber: 'FLG-713',
    manufacturer: 'Sanofi-Aventis',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 320).toISOString(),
    quantity: 220,
    lowStockThreshold: 30,
    purchasePrice: 330,
    mrp: 420,
    sellingPrice: 370,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-05',
    barcode: '8964000120059',
    name: 'Brufen 400mg Tablets',
    batchNumber: 'BRF-609',
    manufacturer: 'Abbott Laboratories',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 340).toISOString(),
    quantity: 180,
    lowStockThreshold: 30,
    purchasePrice: 460,
    mrp: 580,
    sellingPrice: 510,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-06',
    barcode: '8964000120066',
    name: 'Risek 20mg Capsules',
    batchNumber: 'RSK-311',
    manufacturer: 'Getz Pharma',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 300).toISOString(),
    quantity: 95,
    lowStockThreshold: 20,
    purchasePrice: 260,
    mrp: 330,
    sellingPrice: 290,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-07',
    barcode: '8964000120073',
    name: 'Arinac Forte Tablets',
    batchNumber: 'ARN-505',
    manufacturer: 'Abbott Laboratories',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 250).toISOString(),
    quantity: 140,
    lowStockThreshold: 25,
    purchasePrice: 340,
    mrp: 430,
    sellingPrice: 380,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-08',
    barcode: '8964000120080',
    name: 'Gravinate 50mg Tablets',
    batchNumber: 'GRV-220',
    manufacturer: 'Searle Company',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 290).toISOString(),
    quantity: 200,
    lowStockThreshold: 30,
    purchasePrice: 200,
    mrp: 270,
    sellingPrice: 230,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-09',
    barcode: '8964000120097',
    name: 'Ponstan Forte 500mg',
    batchNumber: 'PST-118',
    manufacturer: 'Pfizer Pakistan',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 380).toISOString(),
    quantity: 160,
    lowStockThreshold: 30,
    purchasePrice: 500,
    mrp: 630,
    sellingPrice: 550,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-10',
    barcode: '8964000120103',
    name: 'Surbex-Z High Potency Tablets',
    batchNumber: 'SBZ-704',
    manufacturer: 'Abbott Laboratories',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 420).toISOString(),
    quantity: 85,
    lowStockThreshold: 20,
    purchasePrice: 300,
    mrp: 385,
    sellingPrice: 340,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-11',
    barcode: '8964000120110',
    name: 'Cac-1000 Plus Orange Effervescent',
    batchNumber: 'CAC-921',
    manufacturer: 'GlaxoSmithKline (GSK)',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 210).toISOString(),
    quantity: 110,
    lowStockThreshold: 25,
    purchasePrice: 230,
    mrp: 300,
    sellingPrice: 260,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-12',
    barcode: '8964000120127',
    name: 'Klaricid 250mg Suspension 60ml',
    batchNumber: 'KLR-403',
    manufacturer: 'Abbott Laboratories',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 180).toISOString(),
    quantity: 45,
    lowStockThreshold: 15,
    purchasePrice: 420,
    mrp: 530,
    sellingPrice: 470,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-13',
    barcode: '8964000120134',
    name: 'Citaro 10mg Tablets',
    batchNumber: 'CTR-881',
    manufacturer: 'Hilton Pharma',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 310).toISOString(),
    quantity: 70,
    lowStockThreshold: 20,
    purchasePrice: 270,
    mrp: 350,
    sellingPrice: 305,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-14',
    barcode: '8964000120141',
    name: 'Xb 20mg Tablets',
    batchNumber: 'XBB-109',
    manufacturer: 'Bosch Pharmaceuticals',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 260).toISOString(),
    quantity: 60,
    lowStockThreshold: 15,
    purchasePrice: 300,
    mrp: 390,
    sellingPrice: 340,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-15',
    barcode: '8964000120158',
    name: 'Flyp 500ml IV Infusion',
    batchNumber: 'FLP-650',
    manufacturer: 'UniPharma Laboratories',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 200).toISOString(),
    quantity: 12,
    lowStockThreshold: 25,
    purchasePrice: 85,
    mrp: 120,
    sellingPrice: 100,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-16',
    barcode: '8964000120165',
    name: '5% Dextrose Water 1000ml UNI',
    batchNumber: 'DXT-100',
    manufacturer: 'Uni-Pack Healthcare',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 190).toISOString(),
    quantity: 5,
    lowStockThreshold: 20,
    purchasePrice: 120,
    mrp: 165,
    sellingPrice: 140,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-17',
    barcode: '8964000120172',
    name: '5% Dextrose Saline 500ml UNI',
    batchNumber: 'DXS-500',
    manufacturer: 'Uni-Pack Healthcare',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 220).toISOString(),
    quantity: 8,
    lowStockThreshold: 20,
    purchasePrice: 90,
    mrp: 130,
    sellingPrice: 110,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-18',
    barcode: '8964000120189',
    name: '0.9% Normal Saline 1000ml Infusion',
    batchNumber: 'NS-1004',
    manufacturer: 'Otsuka Pakistan',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 330).toISOString(),
    quantity: 25,
    lowStockThreshold: 30,
    purchasePrice: 115,
    mrp: 155,
    sellingPrice: 135,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-19',
    barcode: '8964000120196',
    name: '10CC Bio Disposable Syringes',
    batchNumber: 'SYR-10CC',
    manufacturer: 'Bio-Care Surgical',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 500).toISOString(),
    quantity: 10,
    lowStockThreshold: 50,
    purchasePrice: 1300,
    mrp: 1700,
    sellingPrice: 1500,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-20',
    barcode: '8964000120202',
    name: '5CC Disposable Syringes (Pack of 100)',
    batchNumber: 'SYR-5CC',
    manufacturer: 'Master Care Surgicals',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 480).toISOString(),
    quantity: 45,
    lowStockThreshold: 20,
    purchasePrice: 950,
    mrp: 1250,
    sellingPrice: 1100,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-21',
    barcode: '8964000120219',
    name: '3CC Disposable Syringes (Pack of 100)',
    batchNumber: 'SYR-3CC',
    manufacturer: 'MediPlus Surgicals',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 460).toISOString(),
    quantity: 60,
    lowStockThreshold: 20,
    purchasePrice: 850,
    mrp: 1150,
    sellingPrice: 980,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-22',
    barcode: '8964000120226',
    name: 'Blue Tex Cotton Pad 100g',
    batchNumber: 'BTX-100',
    manufacturer: 'Surgical Plus Pakistan',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 600).toISOString(),
    quantity: 40,
    lowStockThreshold: 15,
    purchasePrice: 180,
    mrp: 250,
    sellingPrice: 215,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-23',
    barcode: '8964000120233',
    name: 'Surgical Cotton Roll 500g',
    batchNumber: 'CTR-500',
    manufacturer: 'Pakistan Surgical Co',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 550).toISOString(),
    quantity: 35,
    lowStockThreshold: 15,
    purchasePrice: 420,
    mrp: 580,
    sellingPrice: 490,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-24',
    barcode: '8964000120240',
    name: 'Crepe Bandage 4 Inch Elastic',
    batchNumber: 'CRB-4IN',
    manufacturer: 'CareBand Medical',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 500).toISOString(),
    quantity: 75,
    lowStockThreshold: 20,
    purchasePrice: 65,
    mrp: 95,
    sellingPrice: 80,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-25',
    barcode: '8964000120257',
    name: 'Adhesive Plaster Surgical Tape 1" x 5yd',
    batchNumber: 'STP-1IN',
    manufacturer: 'SurgiTape Industries',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 450).toISOString(),
    quantity: 60,
    lowStockThreshold: 15,
    purchasePrice: 110,
    mrp: 160,
    sellingPrice: 135,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-26',
    barcode: '8964000120264',
    name: 'IV Cannula 20G Pink (with port)',
    batchNumber: 'CAN-20G',
    manufacturer: 'SafetyMed Instruments',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 400).toISOString(),
    quantity: 90,
    lowStockThreshold: 25,
    purchasePrice: 55,
    mrp: 85,
    sellingPrice: 70,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-27',
    barcode: '8964000120271',
    name: 'IV Cannula 22G Blue (with port)',
    batchNumber: 'CAN-22G',
    manufacturer: 'SafetyMed Instruments',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 400).toISOString(),
    quantity: 80,
    lowStockThreshold: 25,
    purchasePrice: 55,
    mrp: 85,
    sellingPrice: 70,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-28',
    barcode: '8964000120288',
    name: 'Pyodine Antiseptic Solution 10% 450ml',
    batchNumber: 'PYD-450',
    manufacturer: 'Brookes Pharma',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 350).toISOString(),
    quantity: 40,
    lowStockThreshold: 15,
    purchasePrice: 360,
    mrp: 460,
    sellingPrice: 410,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-29',
    barcode: '8964000120295',
    name: 'Surgical Latex Examination Gloves (M - Box of 100)',
    batchNumber: 'GLV-100M',
    manufacturer: 'GlovoMed Surgical',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 480).toISOString(),
    quantity: 55,
    lowStockThreshold: 15,
    purchasePrice: 850,
    mrp: 1150,
    sellingPrice: 990,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-30',
    barcode: '8964000120301',
    name: 'Face Mask 3-Ply Surgical Earloop (Box of 50)',
    batchNumber: 'MSK-50P',
    manufacturer: 'SurgiGuard Medical',
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 500).toISOString(),
    quantity: 120,
    lowStockThreshold: 30,
    purchasePrice: 220,
    mrp: 320,
    sellingPrice: 270,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-calpol-500',
    barcode: '8964000120501',
    name: 'Calpol 500mg Tablets',
    batchNumber: 'CAL-312',
    manufacturer: 'GlaxoSmithKline (GSK)',
    category: 'General Medicines',
    unit: 'STRIP',
    genericId: 'gen-paracetamol',
    genericName: 'Paracetamol',
    strength: '500mg',
    dosageForm: 'Tablet',
    isControlled: false,
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 400).toISOString(),
    quantity: 320,
    lowStockThreshold: 40,
    purchasePrice: 390,
    mrp: 490,
    sellingPrice: 430,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-febrol-500',
    barcode: '8964000120502',
    name: 'Febrol 500mg Tablets',
    batchNumber: 'FEB-890',
    manufacturer: 'Searle Company',
    category: 'General Medicines',
    unit: 'STRIP',
    genericId: 'gen-paracetamol',
    genericName: 'Paracetamol',
    strength: '500mg',
    dosageForm: 'Tablet',
    isControlled: false,
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 450).toISOString(),
    quantity: 210,
    lowStockThreshold: 30,
    purchasePrice: 375,
    mrp: 470,
    sellingPrice: 415,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-valium-10',
    barcode: '8964000120601',
    name: 'Valium 10mg Tablets (Diazepam)',
    batchNumber: 'VAL-091',
    manufacturer: 'Roche Pakistan',
    category: 'Controlled / Narcotics',
    unit: 'STRIP',
    genericId: 'gen-diazepam',
    genericName: 'Diazepam',
    strength: '10mg',
    dosageForm: 'Tablet',
    isControlled: true,
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 320).toISOString(),
    quantity: 45,
    lowStockThreshold: 10,
    purchasePrice: 580,
    mrp: 750,
    sellingPrice: 690,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-xanax-05',
    barcode: '8964000120602',
    name: 'Xanax 0.5mg Tablets (Alprazolam)',
    batchNumber: 'XNX-441',
    manufacturer: 'Pfizer Pakistan',
    category: 'Controlled / Narcotics',
    unit: 'STRIP',
    genericId: 'gen-alprazolam',
    genericName: 'Alprazolam',
    strength: '0.5mg',
    dosageForm: 'Tablet',
    isControlled: true,
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 290).toISOString(),
    quantity: 60,
    lowStockThreshold: 15,
    purchasePrice: 490,
    mrp: 640,
    sellingPrice: 580,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-tramal-50',
    barcode: '8964000120603',
    name: 'Tramal 50mg Capsules (Tramadol)',
    batchNumber: 'TRM-719',
    manufacturer: 'Searle Company',
    category: 'Controlled / Narcotics',
    unit: 'STRIP',
    genericId: 'gen-tramadol',
    genericName: 'Tramadol HCl',
    strength: '50mg',
    dosageForm: 'Capsule',
    isControlled: true,
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 380).toISOString(),
    quantity: 80,
    lowStockThreshold: 20,
    purchasePrice: 620,
    mrp: 810,
    sellingPrice: 740,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'med-lyrica-75',
    barcode: '8964000120604',
    name: 'Lyrica 75mg Capsules (Pregabalin)',
    batchNumber: 'LYR-105',
    manufacturer: 'Pfizer Pakistan',
    category: 'Controlled / Narcotics',
    unit: 'STRIP',
    genericId: 'gen-pregabalin',
    genericName: 'Pregabalin',
    strength: '75mg',
    dosageForm: 'Capsule',
    isControlled: true,
    expiryDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 420).toISOString(),
    quantity: 50,
    lowStockThreshold: 10,
    purchasePrice: 1200,
    mrp: 1550,
    sellingPrice: 1400,
    gstPercentage: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const DUMMY_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-01',
    name: 'IMRAN PRESIDENT SURGICALS',
    contactPerson: 'Imran Ashraf',
    phone: '0321-6549608',
    email: 'imran@presidentsurgicals.pk',
    address: 'Katchery Road, Sargodha',
    paymentTerms: 'Net 15',
    createdAt: new Date().toISOString()
  },
  {
    id: 'sup-02',
    name: 'GSK & ABBOTT PHARMA DISTRIBUTORS',
    contactPerson: 'Shahid Mehmood',
    phone: '0300-8765432',
    email: 'sales@gskdistributors.pk',
    address: 'Medicine Market, Faisalabad',
    paymentTerms: 'Net 30',
    createdAt: new Date().toISOString()
  },
  {
    id: 'sup-03',
    name: 'MEDI SUPPLY & SURGICAL CO',
    contactPerson: 'Rana Tariq',
    phone: '0333-5544332',
    email: 'tariq@medisupply.pk',
    address: 'Circular Road, Lahore',
    paymentTerms: 'Due on Receipt',
    createdAt: new Date().toISOString()
  }
];

export const DUMMY_CUSTOMERS: Party[] = [
  {
    id: 'cust-01',
    name: 'DR SHAHIDA CLINIC SILANWALI',
    partyType: 'Customer',
    contactPerson: 'Dr. Shahida',
    phone: '0301-7890123',
    email: 'drshahida@gmail.com',
    address: 'Main Bazar, Silanwali',
    city: 'Silanwali',
    paymentTerms: 'Net 15',
    openingBalance: 0,
    creditLimit: 100000,
    balance: 7400,
    taxNumber: 'PK-492019-1',
    createdAt: new Date().toISOString()
  },
  {
    id: 'cust-02',
    name: 'NOOR PHARMACY SILANWALI',
    partyType: 'Customer',
    contactPerson: 'Muhammad Noor',
    phone: '0300-6543210',
    email: 'noorpharmacy@gmail.com',
    address: 'Katchery Road, Silanwali',
    city: 'Silanwali',
    paymentTerms: 'Net 30',
    openingBalance: 0,
    creditLimit: 150000,
    balance: 9000,
    taxNumber: 'PK-384910-2',
    createdAt: new Date().toISOString()
  },
  {
    id: 'cust-03',
    name: 'PAKISTAN PHARMACY CHOKERA',
    partyType: 'Customer',
    contactPerson: 'Zahid Hussain',
    phone: '0345-9871234',
    email: 'pakpharma.chokera@gmail.com',
    address: 'Chokera Morr, Kot Momin Road',
    city: 'Kot Momin',
    paymentTerms: 'Net 15',
    openingBalance: 0,
    creditLimit: 200000,
    balance: 18430,
    createdAt: new Date().toISOString()
  },
  {
    id: 'cust-04',
    name: 'SALEEM PHARMACY SILANWALI',
    partyType: 'Customer',
    contactPerson: 'Saleem Akhtar',
    phone: '0321-4567890',
    email: 'saleempharmacy@gmail.com',
    address: 'Opposite THQ Hospital, Silanwali',
    city: 'Silanwali',
    paymentTerms: 'Net 30',
    openingBalance: 0,
    creditLimit: 250000,
    balance: 109040,
    createdAt: new Date().toISOString()
  },
  {
    id: 'cust-05',
    name: 'ADAM CLINIC MOZAMABAAD',
    partyType: 'Customer',
    contactPerson: 'Dr. Adam Khan',
    phone: '0313-1122334',
    email: 'adamclinic@gmail.com',
    address: 'Mozamabad, Sargodha Road',
    city: 'Sargodha',
    paymentTerms: 'Cash',
    openingBalance: 0,
    creditLimit: 50000,
    balance: 2500,
    createdAt: new Date().toISOString()
  }
];

export const forceSeedDemoProducts = async () => {
  // Clear or save all 30 dummy medicines
  for (const m of DUMMY_MEDICINES) {
    await dbMedicines.save(m);
  }
  for (const s of DUMMY_SUPPLIERS) {
    await dbSuppliers.save(s);
  }
  for (const c of DUMMY_CUSTOMERS) {
    await dbSuppliers.save(c as any);
  }

  // Seed purchase order for BLUE TEX PAD and other surgical items from IMRAN PRESIDENT
  const poBlueTex: PurchaseOrder = {
    id: 'po-blue-tex-1',
    poNumber: '1',
    billNumber: '1',
    supplierId: 'sup-01',
    supplierName: 'IMRAN PRESIDENT',
    partyName: 'IMRAN PRESIDENT',
    date: '2026-09-06T10:00:00.000Z',
    paymentType: 'Cash',
    items: [
      { medicineId: 'med-blue-tex', name: 'BLUE TEX PAD', quantity: 120, unit: 'BOX', purchasePrice: 67.00, total: 8040.00 },
      { medicineId: 'med-23', name: 'Surgical Cotton Roll 500g', quantity: 20, unit: 'ROLL', purchasePrice: 420.00, total: 8400.00 },
      { medicineId: 'med-24', name: 'Crepe Bandage 4 Inch Elastic', quantity: 100, unit: 'PCS', purchasePrice: 50.00, total: 5000.00 }
    ],
    subTotal: 21440.00,
    totalAmount: 21440.00,
    paidAmount: 640.00,
    balanceDue: 20800.00,
    status: 'Partial',
    transactionType: 'Purchase'
  };
  await dbPurchaseOrders.save(poBlueTex);

  return DUMMY_MEDICINES.length;
};

export const generateSeedData = async () => {
  // Always ensure Primary Admin user exists
  const currentUsers = await dbAppUsers.getAll();
  if (currentUsers.length === 0) {
    const sampleUsers: AppUserRecord[] = [
      {
        id: 'usr_mbi_admin',
        name: 'M Bilal Inayat',
        emailOrPhone: '03364585863',
        role: 'Primary Admin',
        status: 'Joined',
        passcode: '0000',
        notes: 'Primary Master Admin & License Holder',
        lastActive: 'Just now',
        createdAt: '2026-08-15T10:00:00.000Z',
        updatedAt: new Date().toISOString()
      }
    ];

    for (const u of sampleUsers) {
      await dbAppUsers.save(u);
    }
  }

  // Ensure default Bank Account structure exists (0 balance)
  const currentBanks = await dbBankAccounts.getAll();
  if (currentBanks.length === 0) {
    const meezanBank: BankAccount = {
      id: 'bank-meezan',
      accountDisplayName: 'MEEZAN',
      bankName: 'Meezan Bank Limited',
      accountHolderName: 'MBI INVENTRA',
      accountNumber: '02140103498212',
      ifscCode: 'MEZN0001',
      branchName: 'Medicine Market Branch',
      upiId: '03001234567@raast',
      openingBalance: 0,
      asOfDate: '2026-09-01',
      currentBalance: 0,
      printOnInvoice: true,
      isDefault: true,
      createdAt: '2026-09-01T00:00:00.000Z'
    };

    await dbBankAccounts.save(meezanBank);
  }

  // Ensure Store Settings
  const existingSettings = await dbStoreSettings.get();
  if (!existingSettings) {
    await dbStoreSettings.save(DEFAULT_STORE_SETTINGS);
  }

  // Clean Zero state enforced for all sales, analytics, and metrics
  return;
};

export const clearAllDemoData = async () => {
  try {
    if (typeof window !== 'undefined') {
      localStorage.setItem('mbi_db_cleaned_v1', 'true');
      localStorage.setItem('mbi_zero_reset_v2', 'true');
    }
    await factoryResetAllStores();
  } catch (err) {
    console.error('Error clearing all demo data:', err);
  }
};


